<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260830141204 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create the Role Playhouse script graph and Messenger tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE rph_character (id VARCHAR(255) NOT NULL, name VARCHAR(128) NOT NULL, script_id VARCHAR(128) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_26ED009BA1C01850 ON rph_character (script_id)');
        $this->addSql('CREATE UNIQUE INDEX character_name ON rph_character (script_id, name)');
        $this->addSql('CREATE TABLE rph_scene (id VARCHAR(160) NOT NULL, sequence INT NOT NULL, heading VARCHAR(255) NOT NULL, script_id VARCHAR(128) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CED6CE0AA1C01850 ON rph_scene (script_id)');
        $this->addSql('CREATE UNIQUE INDEX scene_sequence ON rph_scene (script_id, sequence)');
        $this->addSql('CREATE TABLE rph_script (id VARCHAR(128) NOT NULL, title VARCHAR(255) NOT NULL, source_filename VARCHAR(255) NOT NULL, content TEXT NOT NULL, credit VARCHAR(255) DEFAULT NULL, author VARCHAR(255) DEFAULT NULL, source VARCHAR(255) DEFAULT NULL, imported_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE rph_script_element (id VARCHAR(192) NOT NULL, sequence INT NOT NULL, type VARCHAR(255) NOT NULL, text TEXT NOT NULL, scene_id VARCHAR(160) NOT NULL, character_id VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_92A32B26166053B4 ON rph_script_element (scene_id)');
        $this->addSql('CREATE INDEX IDX_92A32B261136BE75 ON rph_script_element (character_id)');
        $this->addSql('CREATE UNIQUE INDEX element_sequence ON rph_script_element (scene_id, sequence)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE rph_character ADD CONSTRAINT FK_26ED009BA1C01850 FOREIGN KEY (script_id) REFERENCES rph_script (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rph_scene ADD CONSTRAINT FK_CED6CE0AA1C01850 FOREIGN KEY (script_id) REFERENCES rph_script (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rph_script_element ADD CONSTRAINT FK_92A32B26166053B4 FOREIGN KEY (scene_id) REFERENCES rph_scene (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rph_script_element ADD CONSTRAINT FK_92A32B261136BE75 FOREIGN KEY (character_id) REFERENCES rph_character (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE rph_character DROP CONSTRAINT FK_26ED009BA1C01850');
        $this->addSql('ALTER TABLE rph_scene DROP CONSTRAINT FK_CED6CE0AA1C01850');
        $this->addSql('ALTER TABLE rph_script_element DROP CONSTRAINT FK_92A32B26166053B4');
        $this->addSql('ALTER TABLE rph_script_element DROP CONSTRAINT FK_92A32B261136BE75');
        $this->addSql('DROP TABLE rph_character');
        $this->addSql('DROP TABLE rph_scene');
        $this->addSql('DROP TABLE rph_script');
        $this->addSql('DROP TABLE rph_script_element');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
